data:
  type: datasets.smlm_datasets
  data_dir: /repos/datasets/smlm_pc
  dataset_name: mito_pc_16384_2048.h5
  num_workers: 4
  tr_max_sample_points: 2048
  te_max_sample_points: 2048
  batch_size: 16
  dataset_scale: 0.9
  is_scale_z: True
  is_random_sample: True
  noise_points_ratio: 0.0
  transforms: False
  # TODO: add transforms params

viz:
  log_freq: 20  # step
  viz_freq: 240  # step
  save_freq: 50  # epoch
  val_freq: 1  # epoch

trainer:
  fast_dev_run: False
  type: trainers.ae_trainer_3D
  epochs: 120
  seed: 100
  sigma_begin: 1
  sigma_end: 0.01
  sigma_num: 10
  loss_type: "fix_sigma"
  scale_gt: True
  surface: False
  mixture: False
  opt_dec:
    type: 'adam'
    lr: 1e-5  #  use bs*1e-5/8
    beta1: 0.9
    beta2: 0.999
    momentum: 0.9  # for SGD
    weight_decay: 0.
    # scheduler: linear
    # step_epoch: 1000
    # start_ratio: 0.35
    # duration_ratio: 0.5
  opt_enc:
    type: 'adam'
    lr: 1e-5
    beta1: 0.9
    beta2: 0.999
    momentum: 0.9  # for SGD
    weight_decay: 0.
    # scheduler: linear
    # step_epoch: 1000
    # start_ratio: 0.35
    # duration_ratio: 0.5

models:
  scorenet:
    type: models.decoders.resnet_add
    dim: 3
    out_dim: 3
    hidden_size: 256
    n_blocks: 24
    sigma_condition: True
    param_likelihood: False
    xyz_condition: True
    z_dim: 256
  encoder:
    type: models.encoders.l3dp_encoder
    use_deterministic_encoder: True
    zdim: 256 
    input_dim: 3

inference:
  step_size_ratio: 1
  num_steps: 10
  num_points: 16384
  weight: 1
